"""Added category to Book

Revision ID: 941367bd23b5
Revises: 6a91141f604c
Create Date: 2026-03-09 18:54:21.022914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941367bd23b5'
down_revision = '6a91141f604c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
